### PR TITLE
fix: some long standing bugs

### PR DESCRIPTION
**Pull request by manorit2001**

### CODE REVIEW

**Comment by manorit2001** [comment]
@parth-07 add the bug fix you were talking about in this PR and then let's merge this

**Comment by manorit2001** [comment]
ping

**Comment by parth-07** [comment]
> @parth-07 add the bug fix you were talking about in this PR and then let's merge this

Done, I have added that bug fix.

**Review by parth-07 — APPROVED** [review]
Looks good.

**Pull request merged**
